steps:
  # # step 1: authenticate docker with Google Cloud Container Registry
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       gcloud auth configure-docker us-east1-docker.pkg.dev

  # # step 2: build docker image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'build'
  #     - '-t'
  #     - 'airflow-main-img:latest'
  #     - '.'

  # # step 3: tag docker image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'tag'
  #     - 'airflow-main-img:latest'
  #     - 'us-east1-docker.pkg.dev/alpine-life-350508/docker-base-image/airflow-main-img:latest'

  # # step 4: push docker image to Google Cloud Container Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args:
  #     - 'push'
  #     - 'us-east1-docker.pkg.dev/alpine-life-350508/docker-base-image/airflow-main-img:latest'

  # step 5: SSH into VM instance and execute commands from script file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh airflow-instance --zone=asia-southeast2-a --command "cd /home/ragindafirdaus01/setup-airflow/; ls -l"
