steps:
  
  - name: python:3.8.17
    id: 'execute-python-cicd'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        python3 -m pip install --upgrade pip
        pip install --upgrade pip
        pip install -r ./requirements.txt
        python3 ./airflow_metadata.py

options:
  logging: CLOUD_LOGGING_ONLY
