steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'auth-docker-with-artifacts-registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker us-east1-docker.pkg.dev

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'download-ssh-key'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://pipeline-ops/creds/ssh-key-cloudbuild ./ssh-key-cloudbuild \
        && gsutil cp gs://pipeline-ops/creds/ssh-key-cloudbuild.pub ./ssh-key-cloudbuild.pub

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'copy-folder-data-and-dags'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 400 ./ssh-key-cloudbuild \
        && gcloud compute scp --zone=us-central1-a --ssh-key-file=./ssh-key-cloudbuild --recurse data/* instance-20240324-050710:/home/ragindafirdaus01/setup-airflow/data/ \
        && gcloud compute scp --zone=us-central1-a --ssh-key-file=./ssh-key-cloudbuild --recurse dags/* instance-20240324-050710:/home/ragindafirdaus01/setup-airflow/dags/
