steps:

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    args:
      - 'build'
      - '-t'
      - 'airflow-main-img:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'tag-docker-image'
    args:
      - 'tag'
      - 'airflow-main-img:latest'
      - 'us-east1-docker.pkg.dev/alpine-life-350508/docker-base-image/airflow-main-img:latest'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-to-artifacts-registry'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/alpine-life-350508/docker-base-image/airflow-main-img:latest'

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'download-ssh-key'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://pipeline-ops/creds/ssh_key_cloud_build ./ssh_key_cloud_build \
        && gsutil cp gs://pipeline-ops/creds/ssh_key_cloud_build.pub ./ssh_key_cloud_build.pub

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'rerun-docker-container'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 400 ./ssh_key_cloud_build \
        && gcloud compute scp --zone=us-central1-a --ssh-key-file=./ssh_key_cloud_build docker-compose.yaml instance-20240324-050710:/home/ragindafirdaus01/setup-airflow/docker-compose.yaml \
        && gcloud compute ssh instance-20240324-050710 --zone=us-central1-a --ssh-key-file=./ssh_key_cloud_build \
          --command "\
            cd /home/ragindafirdaus01/setup-airflow/; \
            sudo docker compose down; \
            sudo docker compose up -d"
